apiVersion: v1
kind: Service
metadata:
  labels:
    app: n8n
  name: n8n
spec:
  type: NodePort
  ports:
    - name: "5678"
      port: 5678
      targetPort: 5678
  selector:
    app: n8n
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: n8n
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n8n
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/n8n-k8s-default: "true"
        app: n8n
    spec:
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  key: GENERIC_TIMEZONE
                  name: n8n-env
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: n8n-env
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                configMapKeyRef:
                  key: N8N_ENCRYPTION_KEY
                  name: n8n-env
            - name: N8N_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  key: N8N_PROTOCOL
                  name: n8n-env
            - name: N8N_HOST
              valueFrom:
                configMapKeyRef:
                  key: N8N_HOST
                  name: n8n-env
            - name: N8N_PORT
              valueFrom:
                configMapKeyRef:
                  key: N8N_PORT
                  name: n8n-env
          image: n8nio/n8n:latest
          name: n8n
          ports:
            - containerPort: 5678
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-data
      restartPolicy: Always
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
