apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-bot
  template:
    metadata:
      labels:
        app: python-bot
    spec:
      containers:
      - name: python-bot
        image: python-bot:latest
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: TELEGRAM_BOT_TOKEN
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-bot-service
spec:
  selector:
    app: python-bot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000