apiVersion: v1
kind: Namespace
metadata:
  name: mlflow

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.0.1
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.mlflow.svc.cluster.local:5000"
        - name: ARTIFACT_ROOT
          value: "/mlflow"
        - name: BACKEND_STORE_URI
          value: "sqlite:///mlflow.db"
        command: ["mlflow"]
        args: ["server", "--backend-store-uri", "$(BACKEND_STORE_URI)", "--default-artifact-root", "/mlflow", "--host", "0.0.0.0", "--port", "5000"]
        volumeMounts:
        - mountPath: /mlflow
          name: mlflow-storage
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mlflow